### ISSUE TITLE
Potentielle bugs

### ISSUE THREAD

**Issue by RomanHVarinsky** [AestasGIS/QGIS-DMP-Plugin-installation#19]
- Laget **Søbeskyttelseslinjer** er ikke opsat med kodetabeller i listevisning, som beskrevet i vejledningen. 

- Ved indlæsning af **Beskyttede naturtyper** kommer der en fejl om at kodetabellerne ’oprindkode-id’, ’statuskode-id’, ’off-kode-id’, ’cvr-kode-id’, ’natyp-kode-id’, ’aendr-kode-id’ og ’vedligehold-status-id’ kan ikke hentes. Jeg kan dog fint se dem med deres aliasser under Lag. Det betyder så også at kodetabeller med listevisning ikke er opsat.

**Comment by bvthomsen** [comment]
Tilsendte qml filer afprøvet og tilpasset: Attribut dialog er nu udformet som tre faneblade med  attribut felter fordel ud på disse. 
Tilrettede qml filer er tilføjet installations fil dmp_manager.zip på GitHub.
