### ISSUE TITLE
Mulighed for masseupload af data 

### ISSUE THREAD

**Issue by bvthomsen** [AestasGIS/QGIS-DMP-Plugin-installation#22]
Pt. kan man kun "skubbe" (uploade) en feature af gang vha. højreklik på det enkelte feature fundet i difference funktion.
Det ville være ønskeligt med en funktion som enten
- uploadede alle modifikationer nævnt i diffrence funktionen i et hug. 
-  eller man kunne multi-markere (i stedet for enkelt markere) features i træ strukturen for differencer og sende markerede features til upload i et hug.

Estimeret timeforbrug: ca. 10 timer inkl. opdatering af vejledning.

**Comment by RomanHVarinsky** [comment]
Denne funktion betaler Kerteminde Kommune gerne for
