### ISSUE TITLE
Sammenlign redigerings- og referencelag finder ikke forskelle i data.

### ISSUE THREAD

**Issue by JFNI-Skive** [AestasGIS/QGIS-DMP-Plugin-installation#23]
Sammenlign redigerings- og referencelag finder ikke forskelle i data.
Har ændret både geometri og attribut på et objekt, men Data tjek giver ingen resultater.

QGIS-version
3.26.2-Buenos Aires

Database
pg13x64-3.2.3-1

**Comment by bvthomsen** [comment]
Har du husket at sætte det rigtige primary key navn i faneblad "Administration" ? Se vedlagte udklip for Postgres opsætning.
For postgres er det **id** og Primary key quote lig med ingenting

![Udklip](https://user-images.githubusercontent.com/1866520/186920711-720f04c4-c7a8-4da4-bffd-aa228737f6c6.jpg)

**Comment by JFNI-Skive** [comment]
Du har fuldstændig ret. Den havde jeg ikke gennemskuet. Tak!
